### ISSUE TITLE
Could not load the 'vagrant' driver from the load path: Kitchen cannot find Kitchen-Vagrant plugin

### ISSUE THREAD

**Issue by jazchana** [test-kitchen/kitchen-vagrant#244]
I've installed the latest ChefDK and running through one of the kitchen tutorials on the chef site. I'm using a mac osx 10.11. When trying to run kitchen list this is the error message that I see:

```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ClientError
>>>>>> Message: Could not load the 'vagrant' driver from the load path. Please ensure that your driver is installed as a gem or included in your Gemfile if using Bundler.
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

I've seen other issues here that indicate this may be related to multiple or an incompatible versions of kitchen-vagrant gem installed. When I run chef gem list kitchen-vagrant, I see the following:

```
*** LOCAL GEMS ***
kitchen-vagrant (0.20.0)
```

I've tried to uninstall and reinstall the gem as per guidance on other threads (i.e. installing version 0.16.0). However this has not solved the problem.

Also running chef -v gives me the following:

```
Chef Development Kit Version: 0.18.26
chef-client version: 12.14.89
delivery version: master (d86679335580be3de22996ef294b20d525889d8d)
berks version: ERROR
kitchen version: ERROR
```

I don't know why berks and kitchen would say error like this. I'm not a ruby dev so I'm unsure why I'm getting this issue.

Here is the result from kitchen diagnose --all if it helps:

```
---
timestamp: 2016-09-24 14:18:39 UTC
kitchen_version: 1.13.1
plugins:
  error:
    exception: "#<Kitchen::ClientError: Could not load the 'vagrant' driver from the
      load path. Please ensure that your driver is installed as a gem or included
      in your Gemfile if using Bundler.>"
    message: Could not load the 'vagrant' driver from the load path. Please ensure
      that your driver is installed as a gem or included in your Gemfile if using
      Bundler.
    backtrace:
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/driver.rb:50:in
      `rescue in for_plugin'"
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/driver.rb:40:in
      `for_plugin'"
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/config.rb:235:in
      `new_driver'"
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/config.rb:248:in
      `new_instance'"
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/config.rb:144:in
      `block in build_instances'"
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/config.rb:143:in
      `map'"
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/config.rb:143:in
      `with_index'"
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/config.rb:143:in
      `build_instances'"
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/config.rb:119:in
      `instances'"
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/command.rb:115:in
      `filtered_instances'"
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/command.rb:145:in
      `parse_subcommand'"
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/command/diagnose.rb:56:in
      `load_instances'"
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/command/diagnose.rb:35:in
      `block in call'"
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/command/diagnose.rb:80:in
      `record_failure'"
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/command/diagnose.rb:35:in
      `call'"
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/cli.rb:56:in
      `perform'"
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/cli.rb:142:in
      `diagnose'"
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in
      `run'"
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in
      `invoke_command'"
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/cli.rb:334:in
      `invoke_task'"
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'"
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'"
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/bin/kitchen:13:in
      `block in <top (required)>'"
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/errors.rb:174:in
      `with_friendly_errors'"
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/bin/kitchen:13:in
      `<top (required)>'"
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/bin/kitchen:23:in `load'"
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/bin/kitchen:23:in `<main>'"
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'"
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'"
loader:
  process_erb: true
  process_local: true
  process_global: true
  global_config: 
  project_config:
    filename: "/Workspace/clique-infrastructure-repo/cookbooks/motd/.kitchen.yml"
    raw_data:
      driver:
        name: vagrant
      provisioner:
        name: chef_solo
      platforms:
      - name: ubuntu-14.04
      - name: centos-7.2
      suites:
      - name: default
        run_list:
        - recipe[motd::default]
        attributes: 
  local_config: 
  combined_config:
    filename: 
    raw_data:
      driver:
        name: vagrant
      provisioner:
        name: chef_solo
      platforms:
      - name: ubuntu-14.04
      - name: centos-7.2
      suites:
      - name: default
        run_list:
        - recipe[motd::default]
        attributes: 
instances:
  error:
    exception: "#<Kitchen::ClientError: Could not load the 'vagrant' driver from the
      load path. Please ensure that your driver is installed as a gem or included
      in your Gemfile if using Bundler.>"
    message: Could not load the 'vagrant' driver from the load path. Please ensure
      that your driver is installed as a gem or included in your Gemfile if using
      Bundler.
    backtrace:
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/driver.rb:50:in
      `rescue in for_plugin'"
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/driver.rb:40:in
      `for_plugin'"
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/config.rb:235:in
      `new_driver'"
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/config.rb:248:in
      `new_instance'"
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/config.rb:144:in
      `block in build_instances'"
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/config.rb:143:in
      `map'"
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/config.rb:143:in
      `with_index'"
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/config.rb:143:in
      `build_instances'"
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/config.rb:119:in
      `instances'"
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/command.rb:115:in
      `filtered_instances'"
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/command.rb:145:in
      `parse_subcommand'"
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/command/diagnose.rb:56:in
      `load_instances'"
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/command/diagnose.rb:35:in
      `block in call'"
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/command/diagnose.rb:80:in
      `record_failure'"
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/command/diagnose.rb:35:in
      `call'"
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/cli.rb:56:in
      `perform'"
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/cli.rb:142:in
      `diagnose'"
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in
      `run'"
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in
      `invoke_command'"
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/cli.rb:334:in
      `invoke_task'"
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'"
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'"
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/bin/kitchen:13:in
      `block in <top (required)>'"
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/errors.rb:174:in
      `with_friendly_errors'"
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/bin/kitchen:13:in
      `<top (required)>'"
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/bin/kitchen:23:in `load'"
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/bin/kitchen:23:in `<main>'"
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'"
    - "/Users/Jaz/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'"
```

This is the result of chef gem env

```
RubyGems Environment:
  - RUBYGEMS VERSION: 2.6.6
  - RUBY VERSION: 2.3.1 (2016-04-26 patchlevel 112) [x86_64-darwin13]
  - INSTALLATION DIRECTORY: /opt/chefdk/embedded/lib/ruby/gems/2.3.0
  - USER INSTALLATION DIRECTORY: /Users/Jaz/.chefdk/gem/ruby/2.3.0
  - RUBY EXECUTABLE: /opt/chefdk/embedded/bin/ruby
  - EXECUTABLE DIRECTORY: /opt/chefdk/embedded/bin
  - SPEC CACHE DIRECTORY: /Users/Jaz/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /opt/chefdk/embedded/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-13
  - GEM PATHS:
     - /opt/chefdk/embedded/lib/ruby/gems/2.3.0
     - /Users/Jaz/.chefdk/gem/ruby/2.3.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "install" => "--user --no-document"
     - "update" => "--user --no-document"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/Jaz/.rvm/gems/ruby-2.3.0/bin
     - /Users/Jaz/.rvm/gems/ruby-2.3.0@global/bin
     - /Users/Jaz/.rvm/rubies/ruby-2.3.0/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /Library/gradle-2.8/bin
     - /usr/local/mysql/bin
     - /Users/Jaz/Library/Android/sdk/platform-tools
     - /Users/Jaz/Library/Android/sdk/tools
     - /Users/Jaz/.rvm/bin
```

This is the result of my .kitchen/logs/kitchen.log file

```
E, [2016-09-24T15:35:12.586307 #1273] ERROR -- Kitchen: ------Exception-------
E, [2016-09-24T15:35:12.586384 #1273] ERROR -- Kitchen: Class: Kitchen::ClientError
E, [2016-09-24T15:35:12.586402 #1273] ERROR -- Kitchen: Message: Could not load the 'vagrant' driver from the load path. Please ensure that your driver is installed as a gem or included in your Gemfile if using Bundler.
E, [2016-09-24T15:35:12.586414 #1273] ERROR -- Kitchen: ----------------------
E, [2016-09-24T15:35:12.586425 #1273] ERROR -- Kitchen: ------Backtrace-------
E, [2016-09-24T15:35:12.586435 #1273] ERROR -- Kitchen: /Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/driver.rb:50:in `rescue in for_plugin'
E, [2016-09-24T15:35:12.586446 #1273] ERROR -- Kitchen: /Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/driver.rb:40:in `for_plugin'
E, [2016-09-24T15:35:12.586456 #1273] ERROR -- Kitchen: /Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/config.rb:235:in `new_driver'
E, [2016-09-24T15:35:12.586467 #1273] ERROR -- Kitchen: /Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/config.rb:248:in `new_instance'
E, [2016-09-24T15:35:12.586477 #1273] ERROR -- Kitchen: /Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/config.rb:144:in `block in build_instances'
E, [2016-09-24T15:35:12.586487 #1273] ERROR -- Kitchen: /Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/config.rb:143:in `map'
E, [2016-09-24T15:35:12.586497 #1273] ERROR -- Kitchen: /Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/config.rb:143:in `with_index'
E, [2016-09-24T15:35:12.586507 #1273] ERROR -- Kitchen: /Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/config.rb:143:in `build_instances'
E, [2016-09-24T15:35:12.586517 #1273] ERROR -- Kitchen: /Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/config.rb:119:in `instances'
E, [2016-09-24T15:35:12.586528 #1273] ERROR -- Kitchen: /Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/command.rb:115:in `filtered_instances'
E, [2016-09-24T15:35:12.586538 #1273] ERROR -- Kitchen: /Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/command.rb:145:in `parse_subcommand'
E, [2016-09-24T15:35:12.586548 #1273] ERROR -- Kitchen: /Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/command/list.rb:32:in `call'
E, [2016-09-24T15:35:12.586558 #1273] ERROR -- Kitchen: /Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/cli.rb:56:in `perform'
E, [2016-09-24T15:35:12.586569 #1273] ERROR -- Kitchen: /Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/cli.rb:120:in `list'
E, [2016-09-24T15:35:12.586579 #1273] ERROR -- Kitchen: /Users/Jaz/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
E, [2016-09-24T15:35:12.586589 #1273] ERROR -- Kitchen: /Users/Jaz/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
E, [2016-09-24T15:35:12.586599 #1273] ERROR -- Kitchen: /Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/cli.rb:334:in `invoke_task'
E, [2016-09-24T15:35:12.586621 #1273] ERROR -- Kitchen: /Users/Jaz/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
E, [2016-09-24T15:35:12.586632 #1273] ERROR -- Kitchen: /Users/Jaz/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
E, [2016-09-24T15:35:12.586642 #1273] ERROR -- Kitchen: /Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/bin/kitchen:13:in `block in <top (required)>'
E, [2016-09-24T15:35:12.586653 #1273] ERROR -- Kitchen: /Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/errors.rb:174:in `with_friendly_errors'
E, [2016-09-24T15:35:12.586663 #1273] ERROR -- Kitchen: /Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/bin/kitchen:13:in `<top (required)>'
E, [2016-09-24T15:35:12.586673 #1273] ERROR -- Kitchen: /Users/Jaz/.rvm/gems/ruby-2.3.0/bin/kitchen:23:in `load'
E, [2016-09-24T15:35:12.586683 #1273] ERROR -- Kitchen: /Users/Jaz/.rvm/gems/ruby-2.3.0/bin/kitchen:23:in `<main>'
E, [2016-09-24T15:35:12.586698 #1273] ERROR -- Kitchen: /Users/Jaz/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
E, [2016-09-24T15:35:12.586709 #1273] ERROR -- Kitchen: /Users/Jaz/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
E, [2016-09-24T15:35:12.586719 #1273] ERROR -- Kitchen: ----End Backtrace-----
E, [2016-09-24T15:35:12.586729 #1273] ERROR -- Kitchen: ---Nested Exception---
E, [2016-09-24T15:35:12.586739 #1273] ERROR -- Kitchen: Class: LoadError
E, [2016-09-24T15:35:12.586749 #1273] ERROR -- Kitchen: Message: cannot load such file -- kitchen/driver/vagrant
E, [2016-09-24T15:35:12.586759 #1273] ERROR -- Kitchen: ----------------------
E, [2016-09-24T15:35:12.586768 #1273] ERROR -- Kitchen: ------Backtrace-------
E, [2016-09-24T15:35:12.586778 #1273] ERROR -- Kitchen: /Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/driver.rb:50:in `rescue in for_plugin'
E, [2016-09-24T15:35:12.586788 #1273] ERROR -- Kitchen: /Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/driver.rb:40:in `for_plugin'
E, [2016-09-24T15:35:12.586798 #1273] ERROR -- Kitchen: /Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/config.rb:235:in `new_driver'
E, [2016-09-24T15:35:12.586808 #1273] ERROR -- Kitchen: /Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/config.rb:248:in `new_instance'
E, [2016-09-24T15:35:12.586818 #1273] ERROR -- Kitchen: /Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/config.rb:144:in `block in build_instances'
E, [2016-09-24T15:35:12.586828 #1273] ERROR -- Kitchen: /Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/config.rb:143:in `map'
E, [2016-09-24T15:35:12.586838 #1273] ERROR -- Kitchen: /Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/config.rb:143:in `with_index'
E, [2016-09-24T15:35:12.586848 #1273] ERROR -- Kitchen: /Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/config.rb:143:in `build_instances'
E, [2016-09-24T15:35:12.586858 #1273] ERROR -- Kitchen: /Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/config.rb:119:in `instances'
E, [2016-09-24T15:35:12.586868 #1273] ERROR -- Kitchen: /Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/command.rb:115:in `filtered_instances'
E, [2016-09-24T15:35:12.586878 #1273] ERROR -- Kitchen: /Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/command.rb:145:in `parse_subcommand'
E, [2016-09-24T15:35:12.586889 #1273] ERROR -- Kitchen: /Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/command/list.rb:32:in `call'
E, [2016-09-24T15:35:12.586898 #1273] ERROR -- Kitchen: /Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/cli.rb:56:in `perform'
E, [2016-09-24T15:35:12.586909 #1273] ERROR -- Kitchen: /Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/cli.rb:120:in `list'
E, [2016-09-24T15:35:12.586918 #1273] ERROR -- Kitchen: /Users/Jaz/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
E, [2016-09-24T15:35:12.586929 #1273] ERROR -- Kitchen: /Users/Jaz/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
E, [2016-09-24T15:35:12.586938 #1273] ERROR -- Kitchen: /Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/cli.rb:334:in `invoke_task'
E, [2016-09-24T15:35:12.586948 #1273] ERROR -- Kitchen: /Users/Jaz/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
E, [2016-09-24T15:35:12.586958 #1273] ERROR -- Kitchen: /Users/Jaz/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
E, [2016-09-24T15:35:12.586968 #1273] ERROR -- Kitchen: /Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/bin/kitchen:13:in `block in <top (required)>'
E, [2016-09-24T15:35:12.586978 #1273] ERROR -- Kitchen: /Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/lib/kitchen/errors.rb:174:in `with_friendly_errors'
E, [2016-09-24T15:35:12.586988 #1273] ERROR -- Kitchen: /Users/Jaz/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.13.1/bin/kitchen:13:in `<top (required)>'
E, [2016-09-24T15:35:12.587001 #1273] ERROR -- Kitchen: /Users/Jaz/.rvm/gems/ruby-2.3.0/bin/kitchen:23:in `load'
E, [2016-09-24T15:35:12.587012 #1273] ERROR -- Kitchen: /Users/Jaz/.rvm/gems/ruby-2.3.0/bin/kitchen:23:in `<main>'
E, [2016-09-24T15:35:12.587021 #1273] ERROR -- Kitchen: /Users/Jaz/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
E, [2016-09-24T15:35:12.587031 #1273] ERROR -- Kitchen: /Users/Jaz/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
E, [2016-09-24T15:35:12.587041 #1273] ERROR -- Kitchen: ----End Backtrace-----
```

**Comment by cheeseplus** [comment]
I see RVM in there which means you aren't using the ChefDK ruby - you need  to have the Ruby env unpolluted for this to work so I'd drove the RVM loading from your shell and initialize chef in your env

bash example
```
echo 'eval "$(chef shell-init bash)"' >> ~/.bash_profile
```

https://docs.chef.io/install_dk.html

**Comment by mwrock** [comment]
Have you initialized your shell with `chef shell-init`? (see https://github.com/chef/chef-dk#chef-shell-init)

**Comment by jazchana** [comment]
This solved my problem! Thanks.
