### ISSUE TITLE
`kitchen verify` always fails after a full test run 

### ISSUE THREAD

**Issue by pezholio** [test-kitchen/kitchen-vagrant#319]
Hi,

I'm recently getting back in the saddle with test driven infrastructure after a long(ish) break, and I'm trying to add tests to an existing chef repo. I've been having a few issues getting set up so have been running `kitchen test -d never` with a view to diagnosing and fixing problems with the test run by running `kitchen verify` against the infrastructure. However, I'm getting SSH errors when I try this:

```
➔ be kitchen verify
-----> Starting Kitchen (v1.16.0)
-----> Verifying <default-centos-72>...
       Preparing files for transfer
/Users/stuart/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/net-ssh-2.9.4/lib/net/ssh/transport/session.rb:67:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.
/Users/stuart/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/net-ssh-2.9.4/lib/net/ssh/transport/session.rb:84:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.
       [SSH] connection failed, retrying in 1 seconds (#<Timeout::Error: execution expired>)
/Users/stuart/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/net-ssh-2.9.4/lib/net/ssh/transport/session.rb:67:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.
/Users/stuart/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/net-ssh-2.9.4/lib/net/ssh/transport/session.rb:84:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.
       [SSH] connection failed, retrying in 1 seconds (#<Timeout::Error: execution expired>)
/Users/stuart/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/net-ssh-2.9.4/lib/net/ssh/transport/session.rb:67:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.
/Users/stuart/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/net-ssh-2.9.4/lib/net/ssh/transport/session.rb:84:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.
       [SSH] connection failed, retrying in 1 seconds (#<Timeout::Error: execution expired>)
/Users/stuart/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/net-ssh-2.9.4/lib/net/ssh/transport/session.rb:67:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.
/Users/stuart/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/net-ssh-2.9.4/lib/net/ssh/transport/session.rb:84:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.
       [SSH] connection failed, retrying in 1 seconds (#<Timeout::Error: execution expired>)
/Users/stuart/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/net-ssh-2.9.4/lib/net/ssh/transport/session.rb:67:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.
/Users/stuart/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/net-ssh-2.9.4/lib/net/ssh/transport/session.rb:84:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.
$$$$$$ [SSH] connection failed, terminating (#<Timeout::Error: execution expired>)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Verify failed on instance <default-centos-72>.  Please see .kitchen/logs/default-centos-72.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

I can't see anything obvious that's causing this. Any ideas? Here's my kitchen.yml for reference:

```
---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: '12.7.2'
  encrypted_data_bag_secret_key_path: 'data_bag.key'

platforms:
  - name: centos-7.2

suites:
  - name: default
    attributes:
      users:
        fgdev:
          password_hash: 'hash-goes-here'
    run_list:
      - "role[base]"
      - "role[patchwork]"
```

**Comment by pezholio** [comment]
Gonna close this. Turns out one of my firewall recipes was rejecting Vagrant ssh requests as it looked like the IP was spoofed. Not an issue with Kitchen Vagrant.
