### ISSUE TITLE
Unable to run vagrant plugin install --local

### ISSUE THREAD

**Issue by hoshsadiq** [test-kitchen/kitchen-vagrant#396]
I am trying to setup a new project and have got the below config. It seems that the `pre_create_command` runs fine and installs the plugins correctly, however, when kitchen-vagrant goes on to run `vagrant up --no-provision`, vagrant doesn't detect the plugins (logs below). I've also added some info outputting, in the vagrant.rb file, and it seems that `{{vagrant_root}}` is not actually replaced (second log).
```
$ kitchen create
-----> Starting Kitchen (v1.24.0)
       cmd: vagrant --version; cwd:
       vagrant root is: C:/Users/<removed>/desktop/.kitchen/kitchen-vagrant/default-centos7
       finalize_pre_create_command started
WARN: Unresolved specs during Gem::Specification.reset:
      bundler (>= 1.10)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
       Vagrant will now install the following plugins to the local project
       which have been defined in current Vagrantfile:

         vagrant-proxyconf (> 0)
       vagrant-registration (> 0)

       Press ctrl-c to cancel...
       Installing the 'vagrant-proxyconf' plugin. This can take a few minutes...
       Installed the plugin 'vagrant-proxyconf (2.0.0)'!
       Installing the 'vagrant-registration' plugin. This can take a few minutes...
       Installed the plugin 'vagrant-registration (1.3.1)'!
-----> Creating <default-centos7>...
       cmd: vagrant up --provider virtualbox; cwd: C:/Users/<removed>/desktop/.kitchen/kitchen-vagrant/default-centos7
       Vagrant has detected project local plugins configured for this
       project which are not installed.

         vagrant-proxyconf, vagrant-registration
       Install local plugins (Y/N) [N]: Vagrant failed to initialize at a very early stage:

       Vagrant is missing plugins required by the currently loaded Vagrantfile.
       Please install the configured plugins and run this command again. The
       following plugins are currently missing:

         vagrant-proxyconf, vagrant-registration

       To install the plugins configured in the current Vagrantfile run the
       following command:

         vagrant plugin install --local
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [Expected process to exit with [0], but received '1'
---- Begin output of vagrant up --provider virtualbox ----
STDOUT: Vagrant has detected project local plugins configured for this
project which are not installed.

  vagrant-proxyconf, vagrant-registration
Install local plugins (Y/N) [N]:
STDERR: Vagrant failed to initialize at a very early stage:

Vagrant is missing plugins required by the currently loaded Vagrantfile.
Please install the configured plugins and run this command again. The
following plugins are currently missing:

  vagrant-proxyconf, vagrant-registration

To install the plugins configured in the current Vagrantfile run the
following command:

  vagrant plugin install --local
---- End output of vagrant up --provider virtualbox ----
Ran vagrant up --provider virtualbox returned 1] on default-centos7
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```
with the following `.kitchen.yml`
```
# Configure the driver (cloud/hypervisor)
driver:
  name: vagrant

platforms:
  - name: centos7
    driver:
      pre_create_command: vagrant plugin install --local
      provision: true
      box: centos-7
      vagrantfiles:
        - Vagrantfile.local.rb
        - Vagrantfile
      communicator: ssh
      synced_folders:
        - [".", "/vagrant"]
```

And the `{{vagrant_root}}` not being replaced:
```
$ kitchen create
-----> Starting Kitchen (v1.24.0)
       cmd: vagrant --version; cwd:
       vagrant root is: C:/Users/<removed>/desktop/.kitchen/kitchen-vagrant/default-centos7
       finalize_pre_create_command started
WARN: Unresolved specs during Gem::Specification.reset:
      bundler (>= 1.10)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
       ls: cannot access 'vagrant_root': No such file or directory
#<Thread:0x0000000007833428@C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:471 run> terminated with exception (report_on_exception is true):
C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/shell_out.rb:71:in `rescue in run_command': Expected process to exit with [0], but received '2' (Kitchen::ShellOut::ShellCommandFailed)
---- Begin output of ls -la {{vagrant_root}} && vagrant plugin install --local ----
STDOUT:
STDERR: ls: cannot access 'vagrant_root': No such file or directory
---- End output of ls -la {{vagrant_root}} && vagrant plugin install --local ----
Ran ls -la {{vagrant_root}} && vagrant plugin install --local returned 2
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/shell_out.rb:58:in `run_command'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/lifecycle_hooks.rb:111:in `run_local_hook'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/lifecycle_hooks.rb:70:in `block in run'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/lifecycle_hooks.rb:64:in `each'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/lifecycle_hooks.rb:64:in `run'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/lifecycle_hooks.rb:44:in `run_with_hooks'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:381:in `block in transition_to'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:380:in `each'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:380:in `transition_to'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:129:in `create'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/command.rb:197:in `public_send'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ShellOut::ShellCommandFailed
>>>>>> Message: Expected process to exit with [0], but received '2'
---- Begin output of ls -la {{vagrant_root}} && vagrant plugin install --local ----
STDOUT:
STDERR: ls: cannot access 'vagrant_root': No such file or directory
---- End output of ls -la {{vagrant_root}} && vagrant plugin install --local ----
Ran ls -la {{vagrant_root}} && vagrant plugin install --local returned 2
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

**Comment by hoshsadiq** [comment]
Figured out that the pre_create_command actually runs inside the directory where you .kitchen.yml resides. Realised that I could do:
```
pre_create_command: (cd "./.kitchen/kitchen-vagrant/default-centos7" && vagrant plugin install --local)
```
However, the .kitchen dir and the kitchen-vagrant structure isn't setup until after `pre_create_command`.

Lastly, for some reason calling environment variables within `pre_create_command` does not work.
```
pre_create_command: env | grep KITCHEN_INSTANCE_NAME && echo testing KITCHEN_INSTANCE_NAME=$KITCHEN_INSTANCE_NAME && exit 1 
```

output
```
---- Begin output of env | grep KITCHEN_INSTANCE_NAME && echo testing KITCHEN_INSTANCE_NAME=$KITCHEN_INSTANCE_NAME && exit 1 ----
STDOUT: KITCHEN_INSTANCE_NAME=default-centos7
testing KITCHEN_INSTANCE_NAME=$KITCHEN_INSTANCE_NAME
STDERR:
---- End output of env | grep KITCHEN_INSTANCE_NAME && echo testing KITCHEN_INSTANCE_NAME=$KITCHEN_INSTANCE_NAME && exit 1 ----
Ran env | grep KITCHEN_INSTANCE_NAME && echo testing KITCHEN_INSTANCE_NAME=$KITCHEN_INSTANCE_NAME && exit 1 returned 1
```

**Comment by marcparadise** [comment]
Thanks for filing this issue @hoshsadiq. In looking through this, we're trying to understand the use case better - the intent here is to ensure that the plugin is installed before the box is brought up? 

Have you tried modifying the command to ensure it's in the right working dir, like: 
`cd {{vagrant_root}}; vagrant plugin install --local` - or is that failing because the structure is not yet created?

Which leads to your second issue, around vagrant_root not resolving - could you include how/where you're referencing that?

**Comment by hoshsadiq** [comment]
@marcparadise I apologise in advance, I've long left the company so I will not be able to give you anything besides what is in the original ticket, and from what I can remember. In addition, I've not used vagrant and test-kitchen in a while.

> the intent here is to ensure that the plugin is installed before the box is brought up?

That was the aim yes. IIRC running `vagrant plugin install --local` installs the plugins _only_ for the current vagrant box, as for reasons that I don't remember we needed different versions of some plugins for different environments.

> Have you tried modifying the command to ensure it's in the right working dir, like:
> cd {{vagrant_root}}; vagrant plugin install --local - or is that failing because the structure is not yet created?
>
> Which leads to your second issue, around vagrant_root not resolving - could you include how/where you're referencing that?

I think that is what I tried, though I don't remember where I would have put it. Sorry.

Lastly, as far as I'm concerned, I'm happy for this to be closed since it's not gonna be easy to reproduce this. I'll leave it for you to decide.

**Comment by marcparadise** [comment]
Okay,thanks for getting back to me @hoshsadiq; we're going to close this one for now because it's a fairly small corner-case that we haven't otherwise run across.  If it comes up again for you (or anyone else) we can reopen it.
