### ISSUE TITLE
<VagrantPlugins::RDP::Config:0x00000001039ce8f8> (NoMethodError)

### ISSUE THREAD

**Issue by johnjelinek** [test-kitchen/kitchen-vagrant#410]
Have you seen this error?

```
vagrant version
Installed Version: 2.2.5
Latest Version: 2.2.5
 
You're running an up-to-date version of Vagrant!
```

```
bundle exec kitchen create
-----> Starting Kitchen (v2.3.3)
-----> Creating <default-win-2008r2>...
       Bringing machine 'default' up with 'virtualbox' provider...
       ==> default: Checking if box 'devopsgroup-io/windows_server-2012r2-standard-amd64-nocm' version '1.36.0' is up to date...
       ==> default: Machine not provisioned because `--no-provision` is specified.
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [Expected process to exit with [0], but received '1'
---- Begin output of vagrant winrm-config ----
STDOUT: 
STDERR: /opt/vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/lib/vagrant/plugin/v2/config.rb:73:in `method_missing': undefined method `port' for #<VagrantPlugins::RDP::Config:0x00000001039ce8f8> (NoMethodError)
        from /opt/vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/plugins/commands/winrm_config/command.rb:96:in `get_rdp_info'
        from /opt/vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/plugins/commands/winrm_config/command.rb:39:in `block in execute'
        from /opt/vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/lib/vagrant/plugin/v2/command.rb:238:in `block in with_target_vms'
        from /opt/vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/lib/vagrant/plugin/v2/command.rb:232:in `each'
        from /opt/vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/lib/vagrant/plugin/v2/command.rb:232:in `with_target_vms'
        from /opt/vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/plugins/commands/winrm_config/command.rb:35:in `execute'
        from /opt/vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/lib/vagrant/cli.rb:66:in `execute'
        from /opt/vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/lib/vagrant/environment.rb:290:in `cli'
        from /opt/vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/bin/vagrant:182:in `<main>'
---- End output of vagrant winrm-config ----
Ran vagrant winrm-config returned 1] on default-win-2008r2
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

**Comment by johnjelinek** [comment]
This helped me out: https://github.com/test-kitchen/kitchen-vagrant/issues/224#issuecomment-255257608

```
platforms:
  - name: win-2008r2
    driver:
      box: devopsgroup-io/windows_server-2012r2-standard-amd64-nocm
      gui: false
      network:
        - ["forwarded_port", { guest: 3389, host: 33389 }]
```
Adding that `network` stanza fixed it for me.

**Comment by johnjelinek** [comment]
... ran into another error:
```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [Expected process to exit with [0], but received '1'
---- Begin output of vagrant up --no-provision --provider virtualbox ----
STDOUT: Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'devopsgroup-io/windows_server-2012r2-standard-amd64-nocm'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'devopsgroup-io/windows_server-2012r2-standard-amd64-nocm' version '1.36.0' is up to date...
==> default: Setting the name of the VM: kitchen-Ansible-Role-Template-Windows-default-win-2008r2-c7545c32-8af2-43c5-8db8-7d82fc37f91a
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 3389 (guest) => 33389 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
STDERR: The configured shell (config.ssh.shell) is invalid and unable
to properly execute commands. The most common cause for this is
using a shell that is unavailable on the system. Please verify
you're using the full path to the shell and that the shell is
executable by the SSH user.
---- End output of vagrant up --no-provision --provider virtualbox ----
Ran vagrant up --no-provision --provider virtualbox returned 1] on default-win-2008r2
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

If I add `communicator: winrm` to the driver stanza, then I get the original RDP error again.

**Comment by marcparadise** [comment]
@johnjelinek  Could you post your `kitchen.yml` for this issue, if it's still occurring?

**Comment by marcparadise** [comment]
Closing this; if you are able to provide the `kitchen.yml`. please reopen this when doing so.
